spring:
  application:
    name: dealership
  datasource:
    url: jdbc:postgresql://localhost:5432/dealership
    username: dealership
    password: dealership
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
